const features = [
  {
    title: 'AI-Based Distress Detection',
    description: 'Generative AI analyzes voice and text in real time to detect distress and trigger alerts automatically.',
    icon: '🧠',
  },
  {
    title: 'Live GPS Location Sharing',
    description: 'Your precise location is captured and sent with every alert so responders can reach you quickly.',
    icon: '📍',
  },
  {
    title: 'Automated WhatsApp Emergency Alert',
    description: 'Instant WhatsApp alerts to emergency contacts and authorities with incident details and location.',
    icon: '💬',
  },
  {
    title: 'AI-Generated Incident Summary',
    description: 'Clear, concise incident summaries generated by AI for faster response and better coordination.',
    icon: '📋',
  },
]

export default function Features() {
  return (
    <section id="features" className="py-20 md:py-28 px-6 bg-emergency-card/50">
      <div className="max-w-6xl mx-auto">
        <h2 className="font-display font-bold text-3xl sm:text-4xl text-white text-center mb-4">
          How We Keep You Safe
        </h2>
        <p className="text-gray-400 text-center max-w-2xl mx-auto mb-16">
          From detection to dispatch—technology that works when you need it.
        </p>
        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {features.map((f, i) => (
            <div
              key={i}
              className="bg-emergency-dark border border-gray-800 rounded-2xl p-6 hover:border-red-900/50 transition-colors"
            >
              <span className="text-3xl mb-4 block" aria-hidden>{f.icon}</span>
              <h3 className="font-display font-semibold text-lg text-white mb-2">{f.title}</h3>
              <p className="text-gray-400 text-sm leading-relaxed">{f.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}
